name: Cron_job

on:
  schedule:
    - cron: '* * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  check_ssl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2